- name: Install wm and term 
  become: true
  community.general.pacman:
    name: ['hyprland', 'kitty']
    state: latest
  tags: &wmtags ['install','wm']
- name: Install notification manager
  become: true
  community.general.pacman:
    name: ['mako']
    state: latest
  tags: *wmtags
- name: Install screensharing support
  become: true
  community.general.pacman:
    name: ['pipewire', 'wireplumber']
    state: latest
  tags: *wmtags
- name: Install auth agent
  become: true
  community.general.pacman:
    name: ['polkit-kde-agent']
    state: latest
  tags: *wmtags
- name: Install status bar
  become: true
  community.general.pacman:
    name: ['waybar']
    state: latest
  tags: *wmtags
- name: Install app launcher - runtime deps
  become: true
  community.general.pacman:
    name: ['freetype2', 'harfbuz', 'cair', 'pang', 'waylan', 'libxkbcommon']
    state: latest
  tags: *wmtags
- name: Install app launcher - buildtime deps
  become: true
  community.general.pacman:
    name: ['meso', 'scdo', 'wayland-protocols']
    state: latest
  tags: *wmtags
- name: Install app launcher - remove git if existing
  shell: rm -rf ~/tofi
  tags: *wmtags
- name: Install app launcher - pull git
  ansible.builtin.git:
    repo: 'https://github.com/philj56/tofi.git'
    dest: "{{ lookup('env','HOME') }}/tofi"
  tags: *wmtags
- name: Install app launcher - build 
  ansible.builtin.git:
    shell: "cd {{ lookup('env','HOME') }}/tofi && meson build && ninja -C build install"
  tags: *wmtags
