- name: touch .ssh dir
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: install ssh
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: install ssh pub
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
- name: install ssh known_hosts
  copy:
    src: "./.ssh/known_hosts"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
# - name: setup authorized keys
#   authorized_key:
#     user: "{{ lookup('env', 'USER') }}"
#     state: present
#     key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
#   with_fileglob:
#     - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"


