- name: Install ZSH
  community.general.pacman:
    name: zsh
    state: latest
  become: true
  tags: &tags_for_zsh_tasks [ 'install', 'dotfiles', 'zsh' ]
- name: change shell to ZSH
  shell: chsh -s $(which zsh) {{user}}
  become: true
  tags: *tags_for_zsh_tasks
- name: check that ohmyzsh conf exists
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks
- name: install ohmyzsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False
  become: true
- name: install autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks
- name: sym link .zshrc
  file:
    src: "~/.dotfiles/.zshrc"
    dest: "~/.zshrc"
    state: link
  tags: *tags_for_zsh_tasks
- name: sym link .zsh_profile
  file:
    src: "~/.dotfiles/.zsh_profile"
    dest: "~/.zsh_profile"
    state: link
  tags: *tags_for_zsh_tasks
